/*
 * This file is generated by jOOQ.
 */
package org.example.infrastructure.db.keys


import org.example.infrastructure.db.tables.Match
import org.example.infrastructure.db.tables.Player
import org.example.infrastructure.db.tables.PlayerSnapshot
import org.example.infrastructure.db.tables.records.MatchRecord
import org.example.infrastructure.db.tables.records.PlayerRecord
import org.example.infrastructure.db.tables.records.PlayerSnapshotRecord
import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val MATCH_PKEY: UniqueKey<MatchRecord> = Internal.createUniqueKey(Match.MATCH, DSL.name("match_pkey"), arrayOf(Match.MATCH.ID), true)
val PLAYER_PKEY: UniqueKey<PlayerRecord> = Internal.createUniqueKey(Player.PLAYER, DSL.name("player_pkey"), arrayOf(Player.PLAYER.ID), true)
val PLAYER_PUUID_KEY: UniqueKey<PlayerRecord> = Internal.createUniqueKey(Player.PLAYER, DSL.name("player_puuid_key"), arrayOf(Player.PLAYER.PUUID), true)
val PLAYER_SNAPSHOT_PKEY: UniqueKey<PlayerSnapshotRecord> = Internal.createUniqueKey(PlayerSnapshot.PLAYER_SNAPSHOT, DSL.name("player_snapshot_pkey"), arrayOf(PlayerSnapshot.PLAYER_SNAPSHOT.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val MATCH__MATCH_PLAYER_ID_FKEY: ForeignKey<MatchRecord, PlayerRecord> = Internal.createForeignKey(Match.MATCH, DSL.name("match_player_id_fkey"), arrayOf(Match.MATCH.PLAYER_ID), org.example.infrastructure.db.keys.PLAYER_PKEY, arrayOf(Player.PLAYER.ID), true)
val PLAYER_SNAPSHOT__PLAYER_SNAPSHOT_PLAYER_ID_FKEY: ForeignKey<PlayerSnapshotRecord, PlayerRecord> = Internal.createForeignKey(PlayerSnapshot.PLAYER_SNAPSHOT, DSL.name("player_snapshot_player_id_fkey"), arrayOf(PlayerSnapshot.PLAYER_SNAPSHOT.PLAYER_ID), org.example.infrastructure.db.keys.PLAYER_PKEY, arrayOf(Player.PLAYER.ID), true)
