spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/valorant_tracker
    username: tracker
    password: tracker
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1