/*
 * This file is generated by jOOQ.
 */
package org.example.infrastructure.db


import kotlin.collections.List

import org.example.infrastructure.db.tables.Match
import org.example.infrastructure.db.tables.Player
import org.example.infrastructure.db.tables.PlayerSnapshot
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.match</code>.
     */
    val MATCH: Match get() = Match.MATCH

    /**
     * The table <code>public.player</code>.
     */
    val PLAYER: Player get() = Player.PLAYER

    /**
     * The table <code>public.player_snapshot</code>.
     */
    val PLAYER_SNAPSHOT: PlayerSnapshot get() = PlayerSnapshot.PLAYER_SNAPSHOT

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Match.MATCH,
        Player.PLAYER,
        PlayerSnapshot.PLAYER_SNAPSHOT
    )
}
