/*
 * This file is generated by jOOQ.
 */
package org.example.infrastructure.db.tables.records


import org.example.infrastructure.db.tables.Player
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerRecord() : UpdatableRecordImpl<PlayerRecord>(Player.PLAYER) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var puuid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var tag: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var region: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var wins: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var losses: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised PlayerRecord
     */
    constructor(id: Long? = null, puuid: String? = null, name: String? = null, tag: String? = null, region: String? = null, wins: Int? = null, losses: Int? = null): this() {
        this.id = id
        this.puuid = puuid
        this.name = name
        this.tag = tag
        this.region = region
        this.wins = wins
        this.losses = losses
        resetChangedOnNotNull()
    }
}
