/*
 * This file is generated by jOOQ.
 */
package org.example.infrastructure.db.tables


import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.infrastructure.db.Public
import org.example.infrastructure.db.keys.MATCH_PKEY
import org.example.infrastructure.db.keys.MATCH__MATCH_PLAYER_ID_FKEY
import org.example.infrastructure.db.tables.Player.PlayerPath
import org.example.infrastructure.db.tables.records.MatchRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Match(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, MatchRecord>?,
    parentPath: InverseForeignKey<out Record, MatchRecord>?,
    aliased: Table<MatchRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<MatchRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.match</code>
         */
        val MATCH: Match = Match()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MatchRecord> = MatchRecord::class.java

    /**
     * The column <code>public.match.id</code>.
     */
    val ID: TableField<MatchRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.match.player_id</code>.
     */
    val PLAYER_ID: TableField<MatchRecord, Long?> = createField(DSL.name("player_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.match.played_at</code>.
     */
    val PLAYED_AT: TableField<MatchRecord, OffsetDateTime?> = createField(DSL.name("played_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.match.map</code>.
     */
    val MAP: TableField<MatchRecord, String?> = createField(DSL.name("map"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.match.queue_id</code>.
     */
    val QUEUE_ID: TableField<MatchRecord, String?> = createField(DSL.name("queue_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.match.agent</code>.
     */
    val AGENT: TableField<MatchRecord, String?> = createField(DSL.name("agent"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.match.kills</code>.
     */
    val KILLS: TableField<MatchRecord, Int?> = createField(DSL.name("kills"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.match.deaths</code>.
     */
    val DEATHS: TableField<MatchRecord, Int?> = createField(DSL.name("deaths"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.match.assists</code>.
     */
    val ASSISTS: TableField<MatchRecord, Int?> = createField(DSL.name("assists"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.match.won</code>.
     */
    val WON: TableField<MatchRecord, Boolean?> = createField(DSL.name("won"), SQLDataType.BOOLEAN.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<MatchRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<MatchRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<MatchRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.match</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.match</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.match</code> table reference
     */
    constructor(): this(DSL.name("match"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MatchRecord>?, parentPath: InverseForeignKey<out Record, MatchRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, MATCH, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class MatchPath : Match, Path<MatchRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MatchRecord>?, parentPath: InverseForeignKey<out Record, MatchRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<MatchRecord>): super(alias, aliased)
        override fun `as`(alias: String): MatchPath = MatchPath(DSL.name(alias), this)
        override fun `as`(alias: Name): MatchPath = MatchPath(alias, this)
        override fun `as`(alias: Table<*>): MatchPath = MatchPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<MatchRecord> = MATCH_PKEY
    override fun getReferences(): List<ForeignKey<MatchRecord, *>> = listOf(MATCH__MATCH_PLAYER_ID_FKEY)

    private lateinit var _player: PlayerPath

    /**
     * Get the implicit join path to the <code>public.player</code> table.
     */
    fun player(): PlayerPath {
        if (!this::_player.isInitialized)
            _player = PlayerPath(this, MATCH__MATCH_PLAYER_ID_FKEY, null)

        return _player;
    }

    val player: PlayerPath
        get(): PlayerPath = player()
    override fun `as`(alias: String): Match = Match(DSL.name(alias), this)
    override fun `as`(alias: Name): Match = Match(alias, this)
    override fun `as`(alias: Table<*>): Match = Match(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Match = Match(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Match = Match(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Match = Match(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Match = Match(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Match = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Match = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Match = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Match = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Match = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Match = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Match = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Match = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Match = where(DSL.notExists(select))
}
