/*
 * This file is generated by jOOQ.
 */
package org.example.infrastructure.db.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.example.infrastructure.db.Public
import org.example.infrastructure.db.keys.MATCH__MATCH_PLAYER_ID_FKEY
import org.example.infrastructure.db.keys.PLAYER_PKEY
import org.example.infrastructure.db.keys.PLAYER_PUUID_KEY
import org.example.infrastructure.db.keys.PLAYER_SNAPSHOT__PLAYER_SNAPSHOT_PLAYER_ID_FKEY
import org.example.infrastructure.db.tables.Match.MatchPath
import org.example.infrastructure.db.tables.PlayerSnapshot.PlayerSnapshotPath
import org.example.infrastructure.db.tables.records.PlayerRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Player(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PlayerRecord>?,
    parentPath: InverseForeignKey<out Record, PlayerRecord>?,
    aliased: Table<PlayerRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PlayerRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.player</code>
         */
        val PLAYER: Player = Player()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerRecord> = PlayerRecord::class.java

    /**
     * The column <code>public.player.id</code>.
     */
    val ID: TableField<PlayerRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.player.puuid</code>.
     */
    val PUUID: TableField<PlayerRecord, String?> = createField(DSL.name("puuid"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.player.name</code>.
     */
    val NAME: TableField<PlayerRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.player.tag</code>.
     */
    val TAG: TableField<PlayerRecord, String?> = createField(DSL.name("tag"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.player.region</code>.
     */
    val REGION: TableField<PlayerRecord, String?> = createField(DSL.name("region"), SQLDataType.VARCHAR(10).nullable(false), this, "")

    /**
     * The column <code>public.player.wins</code>.
     */
    val WINS: TableField<PlayerRecord, Int?> = createField(DSL.name("wins"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.player.losses</code>.
     */
    val LOSSES: TableField<PlayerRecord, Int?> = createField(DSL.name("losses"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    private constructor(alias: Name, aliased: Table<PlayerRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PlayerRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PlayerRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.player</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.player</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.player</code> table reference
     */
    constructor(): this(DSL.name("player"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerRecord>?, parentPath: InverseForeignKey<out Record, PlayerRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PLAYER, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PlayerPath : Player, Path<PlayerRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerRecord>?, parentPath: InverseForeignKey<out Record, PlayerRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PlayerRecord>): super(alias, aliased)
        override fun `as`(alias: String): PlayerPath = PlayerPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PlayerPath = PlayerPath(alias, this)
        override fun `as`(alias: Table<*>): PlayerPath = PlayerPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<PlayerRecord, Long?> = super.getIdentity() as Identity<PlayerRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<PlayerRecord> = PLAYER_PKEY
    override fun getUniqueKeys(): List<UniqueKey<PlayerRecord>> = listOf(PLAYER_PUUID_KEY)

    private lateinit var _match: MatchPath

    /**
     * Get the implicit to-many join path to the <code>public.match</code> table
     */
    fun match(): MatchPath {
        if (!this::_match.isInitialized)
            _match = MatchPath(this, null, MATCH__MATCH_PLAYER_ID_FKEY.inverseKey)

        return _match;
    }

    val match: MatchPath
        get(): MatchPath = match()

    private lateinit var _playerSnapshot: PlayerSnapshotPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.player_snapshot</code> table
     */
    fun playerSnapshot(): PlayerSnapshotPath {
        if (!this::_playerSnapshot.isInitialized)
            _playerSnapshot = PlayerSnapshotPath(this, null, PLAYER_SNAPSHOT__PLAYER_SNAPSHOT_PLAYER_ID_FKEY.inverseKey)

        return _playerSnapshot;
    }

    val playerSnapshot: PlayerSnapshotPath
        get(): PlayerSnapshotPath = playerSnapshot()
    override fun `as`(alias: String): Player = Player(DSL.name(alias), this)
    override fun `as`(alias: Name): Player = Player(alias, this)
    override fun `as`(alias: Table<*>): Player = Player(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Player = Player(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Player = Player(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Player = Player(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Player = Player(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Player = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Player = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Player = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Player = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Player = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Player = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Player = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Player = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Player = where(DSL.notExists(select))
}
