/*
 * This file is generated by jOOQ.
 */
package org.example.infrastructure.db.tables


import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.infrastructure.db.Public
import org.example.infrastructure.db.keys.PLAYER_SNAPSHOT_PKEY
import org.example.infrastructure.db.keys.PLAYER_SNAPSHOT__PLAYER_SNAPSHOT_PLAYER_ID_FKEY
import org.example.infrastructure.db.tables.Player.PlayerPath
import org.example.infrastructure.db.tables.records.PlayerSnapshotRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerSnapshot(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PlayerSnapshotRecord>?,
    parentPath: InverseForeignKey<out Record, PlayerSnapshotRecord>?,
    aliased: Table<PlayerSnapshotRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PlayerSnapshotRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.player_snapshot</code>
         */
        val PLAYER_SNAPSHOT: PlayerSnapshot = PlayerSnapshot()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerSnapshotRecord> = PlayerSnapshotRecord::class.java

    /**
     * The column <code>public.player_snapshot.id</code>.
     */
    val ID: TableField<PlayerSnapshotRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.player_snapshot.player_id</code>.
     */
    val PLAYER_ID: TableField<PlayerSnapshotRecord, Long?> = createField(DSL.name("player_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.player_snapshot.taken_at</code>.
     */
    val TAKEN_AT: TableField<PlayerSnapshotRecord, OffsetDateTime?> = createField(DSL.name("taken_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.player_snapshot.tier_name</code>.
     */
    val TIER_NAME: TableField<PlayerSnapshotRecord, String?> = createField(DSL.name("tier_name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.player_snapshot.rr</code>.
     */
    val RR: TableField<PlayerSnapshotRecord, Int?> = createField(DSL.name("rr"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.player_snapshot.elo</code>.
     */
    val ELO: TableField<PlayerSnapshotRecord, Int?> = createField(DSL.name("elo"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.player_snapshot.wins</code>.
     */
    val WINS: TableField<PlayerSnapshotRecord, Int?> = createField(DSL.name("wins"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.player_snapshot.losses</code>.
     */
    val LOSSES: TableField<PlayerSnapshotRecord, Int?> = createField(DSL.name("losses"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PlayerSnapshotRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PlayerSnapshotRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PlayerSnapshotRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.player_snapshot</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.player_snapshot</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.player_snapshot</code> table reference
     */
    constructor(): this(DSL.name("player_snapshot"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerSnapshotRecord>?, parentPath: InverseForeignKey<out Record, PlayerSnapshotRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PLAYER_SNAPSHOT, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PlayerSnapshotPath : PlayerSnapshot, Path<PlayerSnapshotRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerSnapshotRecord>?, parentPath: InverseForeignKey<out Record, PlayerSnapshotRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PlayerSnapshotRecord>): super(alias, aliased)
        override fun `as`(alias: String): PlayerSnapshotPath = PlayerSnapshotPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PlayerSnapshotPath = PlayerSnapshotPath(alias, this)
        override fun `as`(alias: Table<*>): PlayerSnapshotPath = PlayerSnapshotPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<PlayerSnapshotRecord, Long?> = super.getIdentity() as Identity<PlayerSnapshotRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<PlayerSnapshotRecord> = PLAYER_SNAPSHOT_PKEY
    override fun getReferences(): List<ForeignKey<PlayerSnapshotRecord, *>> = listOf(PLAYER_SNAPSHOT__PLAYER_SNAPSHOT_PLAYER_ID_FKEY)

    private lateinit var _player: PlayerPath

    /**
     * Get the implicit join path to the <code>public.player</code> table.
     */
    fun player(): PlayerPath {
        if (!this::_player.isInitialized)
            _player = PlayerPath(this, PLAYER_SNAPSHOT__PLAYER_SNAPSHOT_PLAYER_ID_FKEY, null)

        return _player;
    }

    val player: PlayerPath
        get(): PlayerPath = player()
    override fun `as`(alias: String): PlayerSnapshot = PlayerSnapshot(DSL.name(alias), this)
    override fun `as`(alias: Name): PlayerSnapshot = PlayerSnapshot(alias, this)
    override fun `as`(alias: Table<*>): PlayerSnapshot = PlayerSnapshot(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlayerSnapshot = PlayerSnapshot(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlayerSnapshot = PlayerSnapshot(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlayerSnapshot = PlayerSnapshot(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PlayerSnapshot = PlayerSnapshot(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PlayerSnapshot = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PlayerSnapshot = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PlayerSnapshot = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PlayerSnapshot = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PlayerSnapshot = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PlayerSnapshot = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PlayerSnapshot = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PlayerSnapshot = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PlayerSnapshot = where(DSL.notExists(select))
}
