/*
 * This file is generated by jOOQ.
 */
package org.example.infrastructure.db.tables.references


import org.example.infrastructure.db.tables.Match
import org.example.infrastructure.db.tables.Player
import org.example.infrastructure.db.tables.PlayerSnapshot



/**
 * The table <code>public.match</code>.
 */
val MATCH: Match = Match.MATCH

/**
 * The table <code>public.player</code>.
 */
val PLAYER: Player = Player.PLAYER

/**
 * The table <code>public.player_snapshot</code>.
 */
val PLAYER_SNAPSHOT: PlayerSnapshot = PlayerSnapshot.PLAYER_SNAPSHOT
